spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test-jwt
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true


  h2:
    console:
      enabled: true

jwt:
  secret: s1BttUnQn57UZmhAynlWa85Dvk0qnzu9sa12Bhdfu31mASDr9uB40AS9ureDwj12rS4jdiofq0u